# This code is copyright (C) (2015) by the University of Hertfordshire and 
# is made available to third parties for research or private study, criticism 
# or review, and for the purpose of reporting on the state of the art, under 
# the normal fair use/fair dealing exceptions in Sections 29 and 30 of the 
# Copyright, Designs and Patents Act 1988. Use of the code under this
# provision is limited to non-commercial use: commercial use requires
# an appropriate licence from the University of Hertfordshire. 

SOURCES = binheap.c ctransitive.c dag.c dfwalk.c \
dynarray.c dynelem.c dynmatrix.c elemlist.c elemqueue.c \
elemstack.c graphtypes.c graphutils.c lub.c lubcross.c \
lubtree.c main.c mineq.c query.c reachhelper.c reachlabel.c \
tfprintutils.c topo.c classes.c timing.c

all:
	gcc -g -Wall $(SOURCES) -o prepro -lm
